[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",             # Mozilla Public License (ucs2 crate)
    "Unicode-3.0",         # Unicode License (unicode-ident crate)
    "Zlib",                # zlib License (foldhash crate) - OSI approved
    "ISC",                 # ISC License (ring, rustls-webpki, untrusted) - OSI approved
    "BSD-3-Clause",        # BSD 3-Clause License (subtle) - OSI approved
    "CDLA-Permissive-2.0", # Community Data License Agreement (webpki-roots)
]

[bans]
multiple-versions = "warn"

[advisories]
ignore = [
    "RUSTSEC-2024-0436", # paste crate unmaintained (low risk)
]

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["ssh://git@github.com/AMDEPYC/uefi-reset"]
unknown-registry = "deny"
unknown-git = "deny"
